dotfiles_dir = ".dotfiles"

[settings]
vars = [ "vars.toml" ]
posthooks = [ "nvim --headless -c 'autocmd User PackerCompileDone quitall' -c 'PackerCompile'" ]

[settings.dots]
# Apps
ghostwriter_theme = { source = "apps/ghostwriter/zer0_theme.json", target = ".config/ghostwriter/themes/zer0_theme.json" }
mpv_config = { source = "apps/mpv.conf", target = ".config/mpv/mpv.conf" }
zathura = { source = "apps/zathura", target = ".config/zathura" }
# Tools
broot = { source = "tools/broot_config.hjson", target = ".config/broot/conf.hjson" }
cargo = { source = "tools/cargo_config.toml", target = ".local/share/cargo/config.toml" }
flameshot = { source = "tools/flameshot.ini", target = ".config/flameshot/flameshot.ini" }
git = { source = "tools/git_config", target = ".config/git/config" }
nvim = { source = "tools/nvim", target = ".config/nvim" }
stylua = { source = "tools/stylua.toml", target = ".config/stylua/stylua.toml" }
# Utils
bashrc = { source = "utils/bashrc", target = ".bashrc" }
fish = { source = "utils/fish/config.fish", target = ".config/fish/config.fish" }
handlr = { source = "utils/handlr.toml", target = ".config/handlr/handlr.toml" }
alacritty = { source = "utils/alacritty", target = ".config/alacritty" }
npm = { source = "utils/npmrc", target = ".config/npm/npmrc" }
paru = { source = "utils/paru.conf", target = ".config/paru/paru.conf" }
python = { source = "utils/pythonrc", target = ".config/python/pythonrc" }
# Scripts
scripts = { source = "scripts", target = "scripts" }
shared_env = { source = "shared_environment_vars.sh", target = ".shared_shell.sh" }
# .desktop files
feh_desktop_file = { source = "de/desktop_files/feh.desktop", target = ".local/share/applications/feh.desktop" }


[profiles.gtk.dots]
gtk3 = { source = "de/gtk/gtk-3.0/settings.ini", target = ".config/gtk-3.0/settings.ini" }
gtk4 = { source = "de/gtk/gtk-4.0/settings.ini", target = ".config/gtk-4.0/settings.ini" }


[profiles.qt.dots]
qt5 = { source = "de/qt/qt5ct.conf", target = ".config/qt5ct/qt5ct.conf" }
qt6 = { source = "de/qt/qt6ct.conf", target = ".config/qt6ct/qt6ct.conf" }
kvantum = { source = "de/qt/Kvantum", target = ".config/Kvantum" }


[profiles.DE_i3]
extra_profiles = [ "gtk", "qt" ]
posthooks = [ "i3-msg reload" ]

[profiles.DE_i3.dots]
i3_config = { source = "de/x11_i3/i3_config", target = ".config/i3/config" }
picom_config = { source = "de/x11_i3/picom.conf", target = ".config/picom/picom.conf" }
polybar = { source = "de/x11_i3/polybar", target = ".config/polybar" }
reshift_config = { source = "de/x11_i3/redshift.conf", target = ".config/redshift/redshift.conf" }
xresources = { source = "de/x11_i3/Xresources", target = ".Xresources" }
xinitrc = { source = "de/x11_i3/xinitrc", target = ".xinitrc" }

rofi = { source = "de/launchers/rofi/config", target = ".config/rofi" }
dunst = { source = "de/notifications_manager/dunstrc", target = ".config/dunst/dunstrc" }

icons = { source = "de/default_icons/index.theme", target = ".icons/default/index.theme" }
