dotfiles_dir = ".dotfiles"

[settings]
vars = [ "vars.toml" ]

[settings.dots]
# Tools
broot = { source = "tools/broot_config.hjson", target = ".config/broot/conf.hjson" }
cargo = { source = "tools/cargo_config.toml", target = ".local/share/cargo/config.toml" }
git = { source = "tools/git_config", target = ".config/git/config" }
nvim = { source = "tools/nvim", target = ".config/nvim" }
stylua = { source = "tools/stylua.toml", target = ".config/stylua/stylua.toml" }
# Utils
bashrc = { source = "utils/bashrc", target = ".bashrc" }
fish = { source = "utils/fish/config.fish", target = ".config/fish/config.fish" }
handlr = { source = "utils/handlr.toml", target = ".config/handlr/handlr.toml" }
npm = { source = "utils/npmrc", target = ".config/npm/npmrc" }
yay = { source = "utils/yay.json", target = ".config/yay/config.json" }
python = { source = "utils/pythonrc", target = ".config/python/pythonrc" }
# Scripts
scripts = { source = "scripts", target = "scripts" }
env_profile = { source = "profile", target = ".profile" }


[profiles.gtk.dots]
gtk3 = { source = "de/gui/gtk/gtk-3.0/settings.ini", target = ".config/gtk-3.0/settings.ini" }
gtk4 = { source = "de/gui/gtk/gtk-4.0/settings.ini", target = ".config/gtk-4.0/settings.ini" }


[profiles.qt.dots]
kvantum = { source = "de/gui/qt/Kvantum", target = ".config/Kvantum" }


[profiles.DE_generic.dots]
# Apps
mpv_config = { source = "apps/mpv.conf", target = ".config/mpv/mpv.conf" }
zathura = { source = "apps/zathura", target = ".config/zathura" }
# Utils
alacritty = { source = "utils/alacritty", target = ".config/alacritty" }

rofi = { source = "de/launchers/rofi/config", target = ".config/rofi" }

pcmanfm = { source = "utils/pcmanfm_qt.conf", target = ".config/pcmanfm-qt/default/settings.conf" }


[profiles.DE_hyprland]
extra_profiles = [ "DE_generic", "gtk", "qt" ]
posthooks = [ "hyprctl reload", "swaync-client -R", "swaync-client -rs" ]

[profiles.DE_hyprland.dots]
hyprland = { source = "de/wayland/hyprland", target = ".config/hypr" }
waybar = { source = "de/wayland/waybar", target = ".config/waybar" }
swaync = { source = "de/wayland/swaync", target = ".config/swaync" }
swaylock = { source = "de/wayland/swaylock_config", target = ".config/swaylock/config" }
swappy = { source = "de/wayland/swappy_config", target = ".config/swappy/config" }
gammastep = { source = "de/wayland/gammastep.ini", target = ".config/gammastep/config.ini" }
