[[verbs]]
invocation = "edit"
key = "enter"
shortcut = "e"
execution = "$EDITOR +{line} {file}"
apply_to = "text_file"
leave_broot = false

[[verbs]]
invocation = "trash"
shortcut = "del"
execution = "gio trash {file}"
leave_broot = false
