theme = "zefr0x"

[editor]
shell = ["dash", "-c"]
line-number = "relative"
auto-save = true
auto-format = false
true-color = true
bufferline = "multiple"
color-modes = true
popup-border = "all"
end-of-line-diagnostics = "hint"
clipboard-provider = "termcode"

[editor.statusline]
left = [
  "mode",
  "spacer",
  "version-control",
  "spacer",
  "diagnostics",
  "read-only-indicator",
  "file-modification-indicator",
]
center = ["spinner", "file-name"]
right = [
  "workspace-diagnostics",
  "selections",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "total-line-numbers",
  "position-percentage",
  "position",
]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "┊"

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"
