general.import = [
  "~/.config/alacritty/keybind.toml",
  "~/.config/alacritty/style.toml",
  "~/.config/alacritty/hints.toml",
]


terminal.shell.program = "/bin/fish"
working_directory = "None"
general.live_config_reload = false
general.ipc_socket = false
env.TERM = "alacritty"


[window]
decorations = "none"
title = "Alacritty"
dynamic_title = true
class.general = "Alacritty"
class.instance = "Alacritty"
decorations_theme_variant = "None"
resize_increments = false


[scrolling]
history = 10000
multiplier = 3


[bell]
animation = "EaseOut"
color = "#ffffff"
duration = 300
# Show notification in Hyprland
command.args = ["notify", "2", "3000", "rgb(960000)", " Alacritty Bell"]
command.program = "hyprctl"


[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"


[mouse]
hide_when_typing = false
