[default]
depends = ["gui", "fish", "helix", "nvim"]

[default.files]
# env profile script
"profile" = "~/.profile"
# all script
# TODO: split them.
"scripts" = "~/.scripts"

# Tools
"tools/broot" = "~/.config/broot"
"tools/cargo_config.toml" ="~/.local/share/cargo/config.toml"
"tools/git_config" = "~/.config/git/config"

# Utils
"utils/bashrc" = "~/.bashrc"
"utils/npmrc" = "~/.config/npm/npmrc"
"utils/yay.json" = "~/.config/yay/config.json"
"utils/pythonrc" = "~/.config/python/pythonrc"

[default.variables]
git.username = ""
git.email = ""


[fish.files]
"utils/fish/config.fish" = "~/.config/fish/config.fish"
"utils/fish/functions" = "~/.config/fish/functions"


[helix.files]
"tools/helix"= "~/.config/helix"


[nvim.files]
"tools/nvim"= "~/.config/nvim"


[gtk.files]
"de/gui/gtk/gtk-3.0/settings.ini" = "~/.config/gtk-3.0/settings.ini"
"de/gui/gtk/gtk-4.0/settings.ini" = "~/.config/gtk-4.0/settings.ini"


[qt.files]
"de/gui/qt/Kvantum" = "~/.config/Kvantum"
"de/gui/qt/kdeglobals" = "~/.config/kdeglobals"


[de]
depends = [ "gtk", "qt" ]

[de.files]
"de/wayland/niri.kdl" = "~/.config/niri/config.kdl"
"de/wayland/hyprland" = "~/.config/hypr"
"de/wayland/waybar" = "~/.config/waybar"
"de/wayland/swaync" = "~/.config/swaync"

"de/wayland/fuzzel/fuzzel.ini" = "~/.config/fuzzel/fuzzel.ini"

[de.variables]
nvidia_driver = false # Only for Nvidia proprietary GPU driver
software_cursors = false # When mirroring display, we should use software cursor.

monitors = [ ]

layouts = [ { xcode = "us", code = "en", name = "الإنْجِلِيزِيَّة", variant = ""}, { xcode = "ara", code = "ar", name = "ٱلْعَرَبِيَّة", variant = ""} ]

# Application IDs regexs to be blocked from screen capture
block_out_from_screen_capture = [ ]


[gui]
depends = ["de"]

[gui.files]
# Apps
"apps/mpv" = "~/.config/mpv"
"apps/zathura" = "~/.config/zathura"
"apps/swayimgrc" = "~/.config/swayimg/config"
# Utils
"utils/alacritty" = "~/.config/alacritty"
"utils/kitty" = "~/.config/kitty"

"utils/pcmanfm_qt.conf" = "~/.config/pcmanfm-qt/default/settings.conf"
